"""Generate immutable libinjection data; no handwritten fingerprint changes."""
import json, pathlib, hashlib
root = pathlib.Path(__file__).resolve().parents[1]
source = root / 'upstream/sqlparse_data.json'
data = json.loads(source.read_text())
words = dict(data['keywords'])
for fp in data['fingerprints']:
    words['0' + fp.upper()] = 'F'
lines = ['// Generated by tools/generate_tables.py; BSD-3-Clause upstream data.',
         '// Source SHA256: ' + hashlib.sha256(source.read_bytes()).hexdigest(),
         'let lookup_entries : Map[String, String] = {']
for key, value in sorted(words.items()):
    lines.append('  ' + json.dumps(key) + ': ' + json.dumps(value) + ',')
lines += ['}', '', 'fn lookup(word : Bytes) -> String {',
          '  lookup_entries.get(upper_text(word)).unwrap_or("")', '}', '']
(root / 'tables.mbt').write_text('\n'.join(lines), encoding='utf-8')
print(len(words), 'entries; keywords', len(data['keywords']), 'fingerprints',len(data['fingerprints']))

